import os
import discord
import random

TOKEN = ''

client = discord.Client()


@client.event
async def on_ready():
  print(f'{client.user} has connected to Discord!')


@client.event
async def on_message(message):
  if message.author == client.user:
    return

#   if message.author.id == 258875858935218188:
#       response = 'shut up ezza'
#       await message.channel.send(response)
#       return

  messageContent = message.content.lower()

  if client.user.mention in messageContent():
    response = 'don\'t talk to me or my son ever again'
    await message.channel.send(response)
    return

  if ('alienpls3' in messageContent):
    response = 'https://media.discordapp.net/attachments/758617780387315755/838040094010769418/alienpls3.gif'
    await message.channel.send(response)
  elif ('get in there' in messageContent or 'lewis' in messageContent):
    response = 'https://media.discordapp.net/attachments/758617780387315755/848889035229364224/get-in-there-lewis.gif'
    await message.channel.send(response)
  elif ('ree' in messageContent or '350798356542521344' in messageContent):
    response = 'https://media.discordapp.net/attachments/758617780387315755/849584432469508116/ree.gif'
    await message.channel.send(response)
  elif ('dead chat' in messageContent or 'deadchat' in messageContent):
    responses = [
      'Hey Vsauce, Michael here. Chat is dead, or is it? You see as long as there is at least one person here chat is technically not dead. But what qualifies as a person? Well, when we talk about a person we are usually talking about a member of the human race. If you and I were speaking face to face the definition would still apply. But with everything being digital, that definition changes. So, we need a new definition of a person. In this case a person is anyone with an account. This anyone does not have to be of the human race; no, they can be simply a machine programmed to perform certain tasks commonly performed by a human. Now this “server” has a couple members who are these kinds of machines. They watch over the chat at all times, in order to be used to moderate and such. Because of them being bots, they constantly are communicating with this server and other servers through behind the scene means. And now because they are communicating with the server, the server is not technically dead as it is being interacting with. Finally, we need to understand that when we talk about chat, we talk about one of three things. Either A, a specific channel; B, the server itself; Or C, a group dm. In this case we are referring to definition B. If you remember from before, the bots are always communicating with the server. Therefore, we can conclude that chat is not dead as long as at least one of the bots are online. Vsauce, out.',
      'Guys look at me im trying to get activity up by indicating how dead the chat is despite knowing that a phrase similar in nature to "dead chat" will only invite other types of meaningless and unrelated spam, which in itself violates one of the rules set in place about keeping discussions relevant to the channel. Knowing that nobody has anything constructive or channel relevant to add i still sent the message anyway, in a last ditch attempt to call attention to how obscure and low traffic the channel has become, unknowing its a futile and counterproductive strategy.',
      'You really need to stop saying dead chat. This lost its charm long ago, you\'re not a comedic genius. You might as well have the "stupid" role but I don\'t have the programming to issue roles based on responses. Just stop. Think of something else to say rather than dead chat. If you can't, then why don't you turn off discord and walk away for a selected period of time until this place shows some activity again? All I\'m saying is stop with the dead chat comments.',
      'You 👈 really 💯 need 😩 to stop 🚫 saying 💬 dead 💀 chat 💬💦. This lost 💸 its charm 🍀 long 🍆 ago 🔙, you\'re not a comedic 😂😎🤪 genius ☺😝🤓. You 👉 might 💪 as well 😤 have the "stupid 💩" role 📝 but 🍑 I 👁🤴 don\'t 🚫 have the programming 📱📺🏂 to issue 😼👌💥 roles 😩 based 👌 on 🔛 responses 🗣🤔😁. Just stop ✋. Think 🤔❓ of something 😅 else 🏿😩 to say 🗣💯 rather 👉 than dead 💀 chat 📱💬. If you 👉 can\'t 🚫, then why 🤔 don\'t 🚫🙅‍♀️ you 👈😱😡 turn ↪ off 📴 discord 🔥 and walk 🚶 away 😐 for a selected 💰 period 🩸 of time ⏰ until this place 🏆 shows 📺 some activity 🏃🏻 again ❌😬? All 💯 I\'m 💘 saying 🗣 is stop 🛑 with the dead ☠ chat 🙇🏿💬 comments 💬🗯.',
      'Guys 👦 look 👀 at me im 💘 trying 😈 to get 🉐 activity 🚬 up ☝ by indicating how dead 💀 the chat ⁉ is despite 🚫 knowing 🤔 that a phrase 🏭 similar 👱 in nature 🌲 to "dead 💀 chat 💬💦" will only invite 😡 other types 💻 of meaningless ❌😰 and unrelated 🛁 spam 🔁, which in itself violates 🚫 one 1️⃣ of the rules 🚷 set 👌 in place 🚩 about 💦 keeping 👉🏻👌🏻👅 discussions 🗣👄 relevant 📈 to the channel 📺. Knowing 💭 that nobody ❌ has anything 😯 constructive or channel 🌍📺 relevant 📈 to add ➕ i 👁 still 🙄 sent 😳 the message ✉ anyway 🔛, in a last 😍 ditch 😈 attempt 🙋 to call 📞 attention 🚨 to how obscure 🐲 and low 🔉 traffic 🚦 the channel 🌍📺 has become 😌, unknowing its a futile 😧📔🈸 and counterproductive strategy ❌⭕.',
      'Well maybe thats okay because have you EVER thought for a second we got lives? No, I bet you didn\'t but you should because we live in a society damnit. Who the hell cares if the chat dies for a minute? Did your ancestors lives through war, pain, and shit for you to just come around saying when a chat is and isn\'t dead? THERE ARE KIDS IN AFRICA WHO ARE DYING AND WOULD EAT ANYTHING JUST TO LIVE AND HERE YOU ARE CARING ABOUT A CHAT BEING DEAD FOR ONE MINUTE. I\'ve had it I think we should all take a stand for this and change persons pov, but how you might ask? Well, first we\'ll need TheBlueBot to be online 24/7 and then we can code it to where TheBlueBot can reply to itself creating a friendly infinite chat. No more of these "WHAT?!?!? UR CHAT DED FOR A SECOND? NERDDDDDDD" We shall rise and KILL the dead.... KILL. THE. DEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDDDD!!!!!!!!!!!!!!!!!!!!!!',
      'On a normal Thursday, Chat was walking down the street to his workplace. He was on his last warn, so he decided to not risk going late he gone through the alleys. When he was in the middle of it, a team of 4 men or women jumped him. He was cooperative. He did everything the robbers told him. Until he recognises one of them. "Jenny!", he exclaims. Jenny says "Ah shit, well we have to do what we have to do." They proceed to stab him multiple times. The robbers scarce, he slowly bleeds out in an alley with no one to hear him, because he was working night shift, and it was night. Chat slowly died.',
      'A foreigner has entered the room, it seemed fine, with the little chat on it. The chat was currently sleeping, purring and snoring like all other chats did. This outsider, however, wasn\'t satisfied with this, after all, they saw a poster for the server saying that there were 80k people on it, and on their mind, that meant that the chat would never, ever rest. With that, the stranger began to scream loudly: "This chat is dead! I demand all of you to resurrect this chat, I need it alive at all costs, and no matter what happens, this chat located inside this room must be alive by the end of this day! Or else, you will all suffer my wrath.". Despite the rambling of the person from the outer lands, the chat was very well alive, and there were evidences of it being awake 8 minutes ago, but despite all of that, it was clearly dead to this annoyed human being. After screaming high enough, two local people decided to approach them. "What are you talking about? This chat was awake few minutes ago", said the puzzled local. "This chat is absolutely dead and if this chat doesn\'t start moving fast enough, then I will scream louder and loud!", shouted the non-local angry person. The chat then woke up, annoyed at the person\'s screams. "Look! This chat is alive!", said the other native. "Yeah, of course it\'s alive, don\'t you know about how chats work?", said the native. It is a common fact that chats are practically immortal, and that the only circumstances that can kill one is the destruction of the room, the bankruptcy of the company specialized on chats and their wellbeing, and the inevitable heat death of the universe. That, however, wasn\'t clear to the stranger, who literally thought that sleeping was a temporary death and that it was prejudicial for the chat. After attempts to calm them down, the foreigner finally screamed: "That\'s it! THIS IS MY RAGE!", screamed them, and they kept screaming As until the local police kicked them out and revoked their free access to the room. With the angry foreigner gone, the ambience on the room has been lightened, and the chat could finally return to sleep once again. The two locals returned to their usual business, as they usually did. Minutes have passed, and the chat had all the wonderful dreams that one could have. A hour has passed, and the two locals have returned to the room and began to talk about their own job, which involved a lot of unusual and interesting experiences. Minutes have passed, and more people joined in, bringing their own contributions to the conversation, and so, the chat woke up, and it was glad to have such a family like that. The family is huge, and there\'s always room for more. And you? You are always welcome to be part of this wonderful family.',
      'omj nobody talkd for 1 minute!?!?!? time to say "ded chat" 100 times and hope people do the laugh!!!!11!!!!!!1111!1!! xddddddddddd',
      'You know guys, I\'ve been thinking about something. This chat has been pretty dead seeing as nobody has talked for a while now. But I feel like that\'s too long of a way to describe it, so I\'ve come up with a brand new nomenclature that\'s gonna blow your minds. You see if you combine the word "chat" with the word "dead" you get the word CHED! It\'s quick, concise, clear, and straight to the point. Whenever the server is inactive, don\'t bother trying to strike up an interesting conversation. Just say ched. It\'s the easiest and most efficient way to revive it! It doesn\'t even matter how long nobody has talked. It could be two hours or two seconds. What\'s the difference? It still means the server is ched. And pointing that out is extremely imperative to the server\'s well-being. If you don\'t respond to literally every instance of the server\'s inactivity with the repeated use of this one word, the server will plunge into darkness and despair as people never send messages ever again. So go on. Repeat the word ched with pride and honor whenever people forget to speak and revel in the sense of fulfillment and power you get from the use of the word ched.',
      'Man, this chat is dead as hell. I\'ve seen some dead chats in my life, and let me tell you, this is a dead one. People - - the best people - - they say, these best people, say, "Donald, you\'re in the deadest chats," and it\'s true. My chats are the deadest chats there are. That failure Obama though, his dead chats aren\'t anywhere near as dead as mine, no. He tries to revive the chat by inviting Mexican rapists, drug dealers, and let me tell you folks, not their best people. But I do believe my chats are the deadest, purest American chats there are, as stagnant as our broken, monopoly-ridden economy. My chats are the deadest, big league. But Obama\'s chats? Sad!`,
      '''Hey 👋 Vsauce 💙😳, Michael 👓 here. Chat ⁉ is dead 💀✋, or is it? You 👈🏼 see 👀 as long 🍆 as there is at least 💯 one 😤😬 person 👨 here chat ⁉ is technically 💡 not dead ☠⚰. But 🍑 what qualifies 🔥💯 as a person 👨? Well 😦, when ⏰ we talk 🗣 about 💦 a person 👨 we are usually 😌 talking 🗣 about 💦 a member 🍆💦 of the human 👤 race 🏃‍♀️. If you 👈 and I 👥 were speaking 🗣 face 😀 to face 👧 the definition 🔥😎 would still 🙄 apply 📄. But 🍑 with everything 💯 being digital 🚫, that definition 📚 changes 🚼. So, we need 👉 a new 👌 definition 📚 of a person 👫. In this case 📋 a person 😕🤔👨 is anyone 🙋🏿‍♂️ with an account 💳. This anyone 🙋 does not have to be of the human 👤 race 🏃‍♀️; no 🙅🏻‍♂️, they can be simply 🔢 a machine 🤖 programmed 💾📱 to perform 🅱 certain 😎 tasks 🚜🐴 commonly 🐩 performed 🅱 by a human 👤. Now this “server” has a couple 👌👀 members 🍆 who are these kinds 🙁 of machines 📠.
They watch 👀 over 😳🙊💦 the chat ⁉ at all 💯 times 🕐, in order 📲🅰🅱 to be used 🎶 to moderate 😬 and such. Because of them being bots 🤖, they constantly 💰 are communicating 🗣 with this server 💁 and other servers ™🍦 through behind ↩ the scene 🎬 means ❓🤔❔. And now because they are communicating 🗣 with the server 💁, the server 💁 is not technically 🥋🤹 dead 💀 as it is being interacting 📲 with. Finally 🙏, we need 👉 to understand 🤔 that when 🍑 we talk 🗣 about 💦 chat ⁉, we talk 🗣💁🏽‍♂️ about 💦 one 😤 of three 3️⃣ things 📴👌. Either 🚫 A, a specific 🐒 channel 📺📡; B 😎, the server ™🍦 itself; Or C 💀, a group 👥 dm 💦. In this case 💼 we are referring 💮 to definition 📐 B 😎.
If you 👉 remember 🤔 from before 😂, the bots 🤖 are always 🕔 communicating 📰 with the server ™🍦. Therefore 😤😡, we can conclude 🔚 that chat 💬 is not dead 💀 as long 🍆 as at least 💯 one 1️⃣ of the bots 🤖 are online 💻. Vsauce 👓, out.'''
    ]
    response = response[random.randint(0, len(responses))
    await.message.channel.send(response)

client.run(TOKEN)
